special_tags = {
    "ace05e": {
        "trigger:string": [], 
        "trigger:special": [
            "<Business:Declare-Bankruptcy>", 
            "<Business:End-Org>", 
            "<Business:Merge-Org>", 
            "<Business:Start-Org>", 
            "<Conflict:Attack>", 
            "<Conflict:Demonstrate>", 
            "<Contact:Meet>", 
            "<Contact:Phone-Write>", 
            "<Justice:Acquit>", 
            "<Justice:Appeal>", 
            "<Justice:Arrest-Jail>", 
            "<Justice:Charge-Indict>", 
            "<Justice:Convict>", 
            "<Justice:Execute>", 
            "<Justice:Extradite>", 
            "<Justice:Fine>", 
            "<Justice:Pardon>", 
            "<Justice:Release-Parole>", 
            "<Justice:Sentence>", 
            "<Justice:Sue>", 
            "<Justice:Trial-Hearing>", 
            "<Life:Be-Born>", 
            "<Life:Die>", 
            "<Life:Divorce>", 
            "<Life:Injure>", 
            "<Life:Marry>", 
            "<Movement:Transport>", 
            "<Personnel:Elect>", 
            "<Personnel:End-Position>", 
            "<Personnel:Nominate>", 
            "<Personnel:Start-Position>", 
            "<Transaction:Transfer-Money>", 
            "<Transaction:Transfer-Ownership>", 
        ], 
        "role:string": [], 
        "role:special": [
            "<Person>",
            "<Entity>",
            "<Defendant>",
            "<Prosecutor>",
            "<Plaintiff>",
            "<Buyer>",
            "<Artifact>",
            "<Seller>",
            "<Destination>",
            "<Origin>",
            "<Vehicle>",
            "<Agent>",
            "<Attacker>",
            "<Target>",
            "<Victim>",
            "<Instrument>",
            "<Giver>",
            "<Recipient>",
            "<Org>",
            "<Place>",
            "<Adjudicator>",
            "<Beneficiary>", 
        ],
    }, 
    "ere": {
        "trigger:string": [], 
        "trigger:special": [
            "<Business:Start-Org>", 
            "<Business:Merge-Org>", 
            "<Business:End-Org>", 
            "<Business:Declare-Bankruptcy>", 
            "<Conflict:Attack>", 
            "<Conflict:Demonstrate>", 
            "<Contact:Meet>", 
            "<Contact:Correspondence>", 
            "<Contact:Broadcast>", 
            "<Contact:Contact>", 
            "<Justice:Arrest-Jail>", 
            "<Justice:Release-Parole>", 
            "<Justice:Trial-Hearing>", 
            "<Justice:Charge-Indict>", 
            "<Justice:Sue>", 
            "<Justice:Convict>", 
            "<Justice:Appeal>", 
            "<Justice:Sentence>", 
            "<Justice:Fine>", 
            "<Justice:Execute>", 
            "<Justice:Extradite>", 
            "<Justice:Acquit>", 
            "<Justice:Pardon>", 
            "<Life:Be-Born>", 
            "<Life:Marry>", 
            "<Life:Divorce>", 
            "<Life:Injure>", 
            "<Life:Die>", 
            "<Movement:Transport-Person>", 
            "<Movement:Transport-Artifact>", 
            "<Manufacture:Artifact>", 
            "<Personnel:Start-Position>", 
            "<Personnel:End-Position>", 
            "<Personnel:Nominate>", 
            "<Personnel:Elect>", 
            "<Transaction:Transfer-Ownership>", 
            "<Transaction:Transfer-Money>", 
            "<Transaction:Transaction>", 
        ], 
        "role:string": [], 
        "role:special": [
            "<Agent>", 
            "<Org>", 
            "<Place>", 
            "<Target>", 
            "<Instrument>", 
            "<Place>", 
            "<Entity>", 
            "<Audience>", 
            "<Person>", 
            "<Defendant>", 
            "<Prosecutor>", 
            "<Adjudicator>",
            "<Plaintiff>", 
            "<Destination>", 
            "<Origin>", 
            "<Victim>", 
            "<Artifact>", 
            "<Beneficiary>", 
            "<Giver>", 
            "<Recipient>", 
            "<Attacker>", 
        ], 
    },
    "mtop": {
        "intent:string": [], 
    },
    "ace05r": {
        "subj:string": [
        ],
        "subj:special": [
            "<ORG>", 
            "<LOC>", 
            "<PER>", 
            "<VEH>", 
            "<GPE>", 
            "<WEA>",
            "<FAC>",
        ],
        "tag:subject": [
            "<S:PER>", "</S:PER>",
            "<S:ORG>", "</S:ORG>",
            "<S:GPE>", "</S:GPE>",
            "<S:LOC>", "</S:LOC>",
            "<S:VEH>", "</S:VEH>",
            "<S:FAC>", "</S:FAC>",
            "<S:WEA>", "</S:WEA>",
        ],
        "tag:entity":[
            "<ent:PER>", "</ent:PER>",
            "<ent:ORG>", "</ent:ORG>",
            "<ent:GPE>", "</ent:GPE>",
            "<ent:LOC>", "</ent:LOC>",
            "<ent:VEH>", "</ent:VEH>",
            "<ent:FAC>", "</ent:FAC>",
            "<ent:WEA>", "</ent:WEA>",
        ],
        "rel:string": [],
        "rel:special":[
            "<PART-WHOLE>",
            "<PHYS>",
            "<PER-SOC>",
            "<ORG-AFF>",
            "<ART>",
            "<GEN-AFF>",
        ],
    },
    "ace04r": {
        "subj:string": [
        ],
        "subj:special": [
            "<ORG>", 
            "<LOC>", 
            "<PER>", 
            "<VEH>", 
            "<GPE>", 
            "<WEA>",
            "<FAC>",
        ],
        "tag:subject": [
            "<S:PER>", "</S:PER>",
            "<S:ORG>", "</S:ORG>",
            "<S:GPE>", "</S:GPE>",
            "<S:LOC>", "</S:LOC>",
            "<S:VEH>", "</S:VEH>",
            "<S:FAC>", "</S:FAC>",
            "<S:WEA>", "</S:WEA>",
        ],
        "tag:entity":[
            "<ent:PER>", "</ent:PER>",
            "<ent:ORG>", "</ent:ORG>",
            "<ent:GPE>", "</ent:GPE>",
            "<ent:LOC>", "</ent:LOC>",
            "<ent:VEH>", "</ent:VEH>",
            "<ent:FAC>", "</ent:FAC>",
            "<ent:WEA>", "</ent:WEA>",
        ],
        "rel:string": [],
        "rel:special":[
            "<EMP-ORG>",
            "<PHYS>",
            "<PER-SOC>",
            "<OTHER-AFF>",
            "<ART>",
            "<GPE-AFF>",
        ],
    },
}

special_tags["ace05zh"] = {
    "trigger:string": special_tags["ace05e"]["trigger:string"], 
    "role:string": special_tags["ace05e"]["role:string"], 
}
special_tags["erees"] = {
    "trigger:string": special_tags["ere"]["trigger:string"], 
    "role:string": special_tags["ere"]["role:string"], 
}
for i in range(2, 10):
    special_tags["ace05e"][f"role:special_{i}d"] = [f"{r[:-1]}{j}>" for r in special_tags["ace05e"]["role:special"] for j in range(1, i+1)]
    special_tags["ere"][f"role:special_{i}d"] = [f"{r[:-1]}{j}>" for r in special_tags["ere"]["role:special"] for j in range(1, i+1)]

evetype_tags = {
    "ace05e": {
        "string": {
            "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
            "Business:End-Org": "Business End Organization", 
            "Business:Merge-Org": "Business Merge Organization", 
            "Business:Start-Org": "Business Start Organization", 
            "Conflict:Attack": "Conflict Attack", 
            "Conflict:Demonstrate": "Conflict Demonstrate", 
            "Contact:Meet": "Contact Meet", 
            "Contact:Phone-Write": "Contact Phone Write", 
            "Justice:Acquit": "Justice Acquit", 
            "Justice:Appeal": "Justice Appeal", 
            "Justice:Arrest-Jail": "Justice Arrest Jail", 
            "Justice:Charge-Indict": "Justice Charge Indict", 
            "Justice:Convict": "Justice Convict", 
            "Justice:Execute": "Justice Execute", 
            "Justice:Extradite": "Justice Extradite", 
            "Justice:Fine": "Justice Fine", 
            "Justice:Pardon": "Justice Pardon", 
            "Justice:Release-Parole": "Justice Release Parole", 
            "Justice:Sentence": "Justice Sentence", 
            "Justice:Sue": "Justice Sue", 
            "Justice:Trial-Hearing": "Justice Trial Hearing", 
            "Life:Be-Born": "Life Born", 
            "Life:Die": "Life Die", 
            "Life:Divorce": "Life Divorce", 
            "Life:Injure": "Life Injure", 
            "Life:Marry": "Life Marry", 
            "Movement:Transport": "Movement Transport", 
            "Personnel:Elect": "Personnel Elect", 
            "Personnel:End-Position": "Personnel End Position", 
            "Personnel:Nominate": "Personnel Nominate", 
            "Personnel:Start-Position": "Personnel Start-Position", 
            "Transaction:Transfer-Money": "Transaction Transfer Money", 
            "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
        }, 
        "special": {
            "Business:Declare-Bankruptcy": "<Business:Declare-Bankruptcy>", 
            "Business:End-Org": "<Business:End-Org>", 
            "Business:Merge-Org": "<Business:Merge-Org>", 
            "Business:Start-Org": "<Business:Start-Org>", 
            "Conflict:Attack": "<Conflict:Attack>", 
            "Conflict:Demonstrate": "<Conflict:Demonstrate>", 
            "Contact:Meet": "<Contact:Meet>", 
            "Contact:Phone-Write": "<Contact:Phone-Write>", 
            "Justice:Acquit": "<Justice:Acquit>", 
            "Justice:Appeal": "<Justice:Appeal>", 
            "Justice:Arrest-Jail": "<Justice:Arrest-Jail>", 
            "Justice:Charge-Indict": "<Justice:Charge-Indict>", 
            "Justice:Convict": "<Justice:Convict>", 
            "Justice:Execute": "<Justice:Execute>", 
            "Justice:Extradite": "<Justice:Extradite>", 
            "Justice:Fine": "<Justice:Fine>", 
            "Justice:Pardon": "<Justice:Pardon>", 
            "Justice:Release-Parole": "<Justice:Release-Parole>", 
            "Justice:Sentence": "<Justice:Sentence>", 
            "Justice:Sue": "<Justice:Sue>", 
            "Justice:Trial-Hearing": "<Justice:Trial-Hearing>", 
            "Life:Be-Born": "<Life:Be-Born>", 
            "Life:Die": "<Life:Die>", 
            "Life:Divorce": "<Life:Divorce>", 
            "Life:Injure": "<Life:Injure>", 
            "Life:Marry": "<Life:Marry>", 
            "Movement:Transport": "<Movement:Transport>", 
            "Personnel:Elect": "<Personnel:Elect>", 
            "Personnel:End-Position": "<Personnel:End-Position>", 
            "Personnel:Nominate": "<Personnel:Nominate>", 
            "Personnel:Start-Position": "<Personnel:Start-Position>", 
            "Transaction:Transfer-Money": "<Transaction:Transfer-Money>", 
            "Transaction:Transfer-Ownership": "<Transaction:Transfer-Ownership>", 
        }, 
    }, 
    "ere": {
        "string": {
            "Business:Start-Org": "Business Start Organization", 
            "Business:Merge-Org": "Business Merge Organization", 
            "Business:End-Org": "Business End Organization", 
            "Business:Declare-Bankruptcy": "Business Declare Bankruptcy", 
            "Conflict:Attack": "Conflict Attack", 
            "Conflict:Demonstrate": "Conflict Demonstrate", 
            "Contact:Meet": "Contact Meet", 
            "Contact:Correspondence": "Contact Correspondence", 
            "Contact:Broadcast": "Contact Broadcast", 
            "Contact:Contact": "Contact Contact", 
            "Justice:Arrest-Jail": "Justice Arrest Jail", 
            "Justice:Release-Parole": "Justice Release Parole", 
            "Justice:Trial-Hearing": "Justice Trial Hearing", 
            "Justice:Charge-Indict": "Justice Charge Indict", 
            "Justice:Sue": "Justice Sue", 
            "Justice:Convict": "Justice Convict", 
            "Justice:Appeal": "Justice Appeal", 
            "Justice:Sentence": "Justice Sentence", 
            "Justice:Fine": "Justice Fine", 
            "Justice:Execute": "Justice Execute", 
            "Justice:Extradite": "Justice Extradite", 
            "Justice:Acquit": "Justice Acquit", 
            "Justice:Pardon": "Justice Pardon", 
            "Life:Be-Born": "Life Born", 
            "Life:Marry": "Life Marry", 
            "Life:Divorce": "Life Divorce", 
            "Life:Injure": "Life Injure", 
            "Life:Die": "Life Die", 
            "Movement:Transport-Person": "Movement Transport Person", 
            "Movement:Transport-Artifact": "Movement Transport Artifact", 
            "Manufacture:Artifact": "Manufacture Artifact", 
            "Personnel:Start-Position": "Personnel Start Position", 
            "Personnel:End-Position": "Personnel End Position", 
            "Personnel:Nominate": "Personnel Nominate", 
            "Personnel:Elect": "Personnel Elect", 
            "Transaction:Transfer-Ownership": "Transaction Transfer Ownership", 
            "Transaction:Transfer-Money": "Transaction Transfer Money", 
            "Transaction:Transaction": "Transaction Transaction", 
        }, 
        "special": {
            "Business:Start-Org": "<Business:Start-Org>", 
            "Business:Merge-Org": "<Business:Merge-Org>", 
            "Business:End-Org": "<Business:End-Org>", 
            "Business:Declare-Bankruptcy": "<Business:Declare-Bankruptcy>", 
            "Conflict:Attack": "<Conflict:Attack>", 
            "Conflict:Demonstrate": "<Conflict:Demonstrate>", 
            "Contact:Meet": "<Contact:Meet>", 
            "Contact:Correspondence": "<Contact:Correspondence>", 
            "Contact:Broadcast": "<Contact:Broadcast>", 
            "Contact:Contact": "<Contact:Contact>", 
            "Justice:Arrest-Jail": "<Justice:Arrest-Jail>", 
            "Justice:Release-Parole": "<Justice:Release-Parole>", 
            "Justice:Trial-Hearing": "<Justice:Trial-Hearing>", 
            "Justice:Charge-Indict": "<Justice:Charge-Indict>", 
            "Justice:Sue": "<Justice:Sue>", 
            "Justice:Convict": "<Justice:Convict>", 
            "Justice:Appeal": "<Justice:Appeal>", 
            "Justice:Sentence": "<Justice:Sentence>", 
            "Justice:Fine": "<Justice:Fine>", 
            "Justice:Execute": "<Justice:Execute>", 
            "Justice:Extradite": "<Justice:Extradite>", 
            "Justice:Acquit": "<Justice:Acquit>", 
            "Justice:Pardon": "<Justice:Pardon>", 
            "Life:Be-Born": "<Life:Be-Born>", 
            "Life:Marry": "<Life:Marry>", 
            "Life:Divorce": "<Life:Divorce>", 
            "Life:Injure": "<Life:Injure>", 
            "Life:Die": "<Life:Die>", 
            "Movement:Transport-Person": "<Movement:Transport-Person>", 
            "Movement:Transport-Artifact": "<Movement:Transport-Artifact>", 
            "Manufacture:Artifact": "<Manufacture:Artifact>", 
            "Personnel:Start-Position": "<Personnel:Start-Position>", 
            "Personnel:End-Position": "<Personnel:End-Position>", 
            "Personnel:Nominate": "<Personnel:Nominate>", 
            "Personnel:Elect": "<Personnel:Elect>", 
            "Transaction:Transfer-Ownership": "<Transaction:Transfer-Ownership>", 
            "Transaction:Transfer-Money": "<Transaction:Transfer-Money>", 
            "Transaction:Transaction": "<Transaction:Transaction>", 
        }, 
    }, 
}

evetype_tags["ace05zh"] = {
    "string": evetype_tags["ace05e"]["string"]
}
evetype_tags["erees"] = {
    "string": evetype_tags["ere"]["string"]
}

role_tags = {
    "ace05e": {
        "string": {
            "Person": "Person",
            "Entity": "Entity",
            "Defendant": "Defendant",
            "Prosecutor": "Prosecutor",
            "Plaintiff": "Plaintiff",
            "Buyer": "Buyer",
            "Artifact": "Artifact",
            "Seller": "Seller",
            "Destination": "Destination",
            "Origin": "Origin",
            "Vehicle": "Vehicle",
            "Agent": "Agent",
            "Attacker": "Attacker",
            "Target": "Target",
            "Victim": "Victim",
            "Instrument": "Instrument",
            "Giver": "Giver",
            "Recipient": "Recipient",
            "Org": "Organization",
            "Place": "Place",
            "Adjudicator": "Adjudicator",
            "Beneficiary": "Beneficiary",
        }, 
        "special": {
            "Person": "<Person>",
            "Entity": "<Entity>",
            "Defendant": "<Defendant>",
            "Prosecutor": "<Prosecutor>",
            "Plaintiff": "<Plaintiff>",
            "Buyer": "<Buyer>",
            "Artifact": "<Artifact>",
            "Seller": "<Seller>",
            "Destination": "<Destination>",
            "Origin": "<Origin>",
            "Vehicle": "<Vehicle>",
            "Agent": "<Agent>",
            "Attacker": "<Attacker>",
            "Target": "<Target>",
            "Victim": "<Victim>",
            "Instrument": "<Instrument>",
            "Giver": "<Giver>",
            "Recipient": "<Recipient>",
            "Org": "<Org>",
            "Place": "<Place>",
            "Adjudicator": "<Adjudicator>",
            "Beneficiary": "<Beneficiary>", 
        }, 
    },
    "ere": {
        "string": {
            "Agent": "Agent", 
            "Org": "Organization", 
            "Place": "Place", 
            "Target": "Target", 
            "Instrument": "Instrument", 
            "Place": "Place", 
            "Entity": "Entity", 
            "Audience": "Audience", 
            "Person": "Person", 
            "Defendant": "Defendant", 
            "Prosecutor": "Prosecutor", 
            "Adjudicator": "Adjudicator",
            "Plaintiff": "Plaintiff", 
            "Destination": "Destination", 
            "Origin": "Origin", 
            "Victim": "Victim", 
            "Artifact": "Artifact", 
            "Beneficiary": "Beneficiary", 
            "Giver": "Giver", 
            "Recipient": "Recipient", 
            "Attacker": "Attacker", 
            "Thing": "Thing", 
        }, 
        "special": {
            "Agent": "<Agent>", 
            "Org": "<Org>", 
            "Place": "<Place>", 
            "Target": "<Target>", 
            "Instrument": "<Instrument>", 
            "Place": "<Place>", 
            "Entity": "<Entity>", 
            "Audience": "<Audience>", 
            "Person": "<Person>", 
            "Defendant": "<Defendant>", 
            "Prosecutor": "<Prosecutor>", 
            "Adjudicator": "<Adjudicator>",
            "Plaintiff": "<Plaintiff>", 
            "Destination": "<Destination>", 
            "Origin": "<Origin>", 
            "Victim": "<Victim>", 
            "Artifact": "<Artifact>", 
            "Beneficiary": "<Beneficiary>", 
            "Giver": "<Giver>", 
            "Recipient": "<Recipient>", 
            "Attacker": "<Attacker>", 
            "Thing": "<Thing>", 
        }, 
    },
}

role_tags["ace05zh"] = {
    "string": role_tags["ace05e"]["string"]
}
role_tags["erees"] = {
    "string": role_tags["ere"]["string"]
}

for i in range(2, 10):
    role_tags["ace05e"][f"special_{i}d"] = {r: " ".join([f"{s[:-1]}{j}>" for j in range(1, i+1)]) for r, s in role_tags["ace05e"][f"special"].items()}
    role_tags["ere"][f"special_{i}d"] = {r: " ".join([f"{s[:-1]}{j}>" for j in range(1, i+1)]) for r, s in role_tags["ere"][f"special"].items()}
    
    
intent_tags = {
    "mtop": {
        "string": {
            'ADD_TIME_TIMER': 'add time timer',
            'ADD_TO_PLAYLIST_MUSIC': 'add to playlist music',
            'ANSWER_CALL': 'answer call',
            'CANCEL_CALL': 'cancel call',
            'CANCEL_MESSAGE': 'cancel message',
            'CREATE_ALARM': 'create alarm',
            'CREATE_CALL': 'create call',
            'CREATE_PLAYLIST_MUSIC': 'create playlist music',
            'CREATE_REMINDER': 'create reminder',
            'CREATE_TIMER': 'create timer',
            'DELETE_ALARM': 'delete alarm',
            'DELETE_PLAYLIST_MUSIC': 'delete playlist music',
            'DELETE_REMINDER': 'delete reminder',
            'DELETE_TIMER': 'delete timer',
            'DISLIKE_MUSIC': 'dislike music',
            'DISPREFER': 'disprefer',
            'END_CALL': 'end call',
            'FAST_FORWARD_MUSIC': 'fast forward music',
            'FOLLOW_MUSIC': 'follow music',
            'GET_AGE': 'get age',
            'GET_AIRQUALITY': 'get airquality',
            'GET_ALARM': 'get alarm',
            'GET_ATTENDEE_EVENT': 'get attendee event',
            'GET_AVAILABILITY': 'get availability',
            'GET_CALL': 'get call',
            'GET_CALL_CONTACT': 'get call contact',
            'GET_CALL_TIME': 'get call time',
            'GET_CATEGORY_EVENT': 'get category event',
            'GET_CONTACT': 'get contact',
            'GET_CONTACT_METHOD': 'get contact method',
            'GET_DATE_TIME_EVENT': 'get date time event',
            'GET_DETAILS_NEWS': 'get details news',
            'GET_EDUCATION_DEGREE': 'get education degree',
            'GET_EDUCATION_TIME': 'get education time',
            'GET_EMPLOYER': 'get employer',
            'GET_EMPLOYMENT_TIME': 'get employment time',
            'GET_EVENT': 'get event',
            'GET_GENDER': 'get gender',
            'GET_GROUP': 'get group',
            'GET_INFO_CONTACT': 'get info contact',
            'GET_INFO_RECIPES': 'get info recipes',
            'GET_JOB': 'get job',
            'GET_LANGUAGE': 'get language',
            'GET_LIFE_EVENT': 'get life event',
            'GET_LIFE_EVENT_TIME': 'get life event time',
            'GET_LOCATION': 'get location',
            'GET_LYRICS_MUSIC': 'get lyrics music',
            'GET_MAJOR': 'get major',
            'GET_MESSAGE': 'get message',
            'GET_MESSAGE_CONTACT': 'get message contact',
            'GET_MUTUAL_FRIENDS': 'get mutual friends',
            'GET_RECIPES': 'get recipes',
            'GET_REMINDER': 'get reminder',
            'GET_REMINDER_AMOUNT': 'get reminder amount',
            'GET_REMINDER_DATE_TIME': 'get reminder date time',
            'GET_REMINDER_LOCATION': 'get reminder location',
            'GET_STORIES_NEWS': 'get stories news',
            'GET_SUNRISE': 'get sunrise',
            'GET_SUNSET': 'get sunset',
            'GET_TIMER': 'get timer',
            'GET_TRACK_INFO_MUSIC': 'get track info music',
            'GET_UNDERGRAD': 'get undergrad',
            'GET_WEATHER': 'get weather',
            'HELP_REMINDER': 'help reminder',
            'HOLD_CALL': 'hold call',
            'IGNORE_CALL': 'ignore call',
            'IS_TRUE_RECIPES': 'is true recipes',
            'LIKE_MUSIC': 'like music',
            'LOOP_MUSIC': 'loop music',
            'MERGE_CALL': 'merge call',
            'PAUSE_MUSIC': 'pause music',
            'PAUSE_TIMER': 'pause timer',
            'PLAY_MEDIA': 'play media',
            'PLAY_MUSIC': 'play music',
            'PREFER': 'prefer',
            'PREVIOUS_TRACK_MUSIC': 'previous track music',
            'QUESTION_MUSIC': 'question music',
            'QUESTION_NEWS': 'question news',
            'REMOVE_FROM_PLAYLIST_MUSIC': 'remove from playlist music',
            'REPEAT_ALL_MUSIC': 'repeat all music',
            'REPEAT_ALL_OFF_MUSIC': 'repeat all off music',
            'REPLAY_MUSIC': 'replay music',
            'RESTART_TIMER': 'restart timer',
            'RESUME_CALL': 'resume call',
            'RESUME_MUSIC': 'resume music',
            'RESUME_TIMER': 'resume timer',
            'REWIND_MUSIC': 'rewind music',
            'SEND_MESSAGE': 'send message',
            'SET_AVAILABLE': 'set available',
            'SET_DEFAULT_PROVIDER_CALLING': 'set default provider calling',
            'SET_DEFAULT_PROVIDER_MUSIC': 'set default provider music',
            'SET_RSVP_INTERESTED': 'set rsvp interested',
            'SET_RSVP_NO': 'set rsvp no',
            'SET_RSVP_YES': 'set rsvp yes',
            'SET_UNAVAILABLE': 'set unavailable',
            'SHARE_EVENT': 'share event',
            'SILENCE_ALARM': 'silence alarm',
            'SKIP_TRACK_MUSIC': 'skip track music',
            'SNOOZE_ALARM': 'snooze alarm',
            'START_SHUFFLE_MUSIC': 'start shuffle music',
            'STOP_MUSIC': 'stop music',
            'STOP_SHUFFLE_MUSIC': 'stop shuffle music',
            'SUBTRACT_TIME_TIMER': 'subtract time timer',
            'SWITCH_CALL': 'switch call',
            'UNLOOP_MUSIC': 'unloop music',
            'UPDATE_ALARM': 'update alarm',
            'UPDATE_CALL': 'update call',
            'UPDATE_METHOD_CALL': 'update method call',
            'UPDATE_REMINDER': 'update reminder',
            'UPDATE_REMINDER_DATE_TIME': 'update reminder date time',
            'UPDATE_REMINDER_LOCATION': 'update reminder location',
            'UPDATE_REMINDER_TODO': 'update reminder todo',
            'UPDATE_TIMER': 'update timer', 
        }, 
    }, 
    "snips": {
        "string": {
            "AddToPlaylist": "add to playlist",
            "BookRestaurant": "book restaurant",
            "GetWeather": "get weather",
            "PlayMusic": "play music",
            "RateBook": "rate book",
            "SearchCreativeWork": "search creative work",
            "SearchScreeningEvent": "search screening event", 
        },
    },
    "atis": {
        "string": {
            "atis_abbreviation": "abbreviation",
            "atis_aircraft": "aircraft",
            "atis_airfare": "airfare",
            "atis_airline": "airline",
            "atis_airport": "airport",
            "atis_capacity": "capacity",
            "atis_cheapest": "cheapest",
            "atis_city": "city",
            "atis_distance": "distance",
            "atis_flight": "flight",
            "atis_flight_no": "flight number",
            "atis_flight_time": "flight time",
            "atis_ground_fare": "ground fare",
            "atis_ground_service": "ground service",
            "atis_meal": "meal",
            "atis_quantity": "quantity",
            "atis_restriction": "restriction",
        },
    },
}

slot_tags = {
    "mtop": {
        "string": {
            "CONTACT": "contact",
            "TYPE_CONTENT": "type content",
            "RECIPIENT": "recipient",
            "LOCATION": "location",
            "DATE_TIME": "date time",
            "ORDINAL": "ordinal",
            "CONTENT_EXACT": "content exact",
            "RECIPES_ATTRIBUTE": "recipes attribute",
            "PERSON_REMINDED": "person reminded",
            "TODO": "todo",
            "NEWS_TYPE": "news type",
            "NEWS_CATEGORY": "news category",
            "RECIPES_DISH": "recipes dish",
            "NEWS_TOPIC": "news topic",
            "SENDER": "sender",
            "MUSIC_TYPE": "music type",
            "MUSIC_ARTIST_NAME": "music artist name",
            "NAME_APP": "name app",
            "WEATHER_ATTRIBUTE": "weather attribute",
            "CATEGORY_EVENT": "category event",
            "MUSIC_PLAYLIST_TITLE": "music playlist title",
            "METHOD_TIMER": "method timer",
            "LIFE_EVENT": "life event",
            "MUSIC_TRACK_TITLE": "music track title",
            "MUSIC_PROVIDER_NAME": "music provider name",
            "CONTACT_ADDED": "contact added",
            "RECIPES_COOKING_METHOD": "recipes cooking method",
            "CONTACT_RELATED": "contact related",
            "TYPE_RELATION": "type relation",
            "AMOUNT": "amount",
            "RECIPES_INCLUDED_INGREDIENT": "recipes included ingredient",
            "NEWS_REFERENCE": "news reference",
            "NEWS_SOURCE": "news source",
            "WEATHER_TEMPERATURE_UNIT": "weather temperature unit",
            "EMPLOYER": "employer",
            "PERIOD": "period",
            "RECIPES_TYPE": "recipes type",
            "EDUCATION_DEGREE": "education degree",
            "MUSIC_GENRE": "music genre",
            "TITLE_EVENT": "title event",
            "TIMER_NAME": "timer name",
            "RECIPES_UNIT_NUTRITION": "recipes unit nutrition",
            "RECIPES_EXCLUDED_INGREDIENT": "recipes excluded ingredient",
            "RECIPES_DIET": "recipes diet",
            "RECIPES_UNIT_MEASUREMENT": "recipes unit measurement",
            "JOB": "job",
            "METHOD_RETRIEVAL_REMINDER": "method retrieval reminder",
            "CONTACT_REMOVED": "contact removed",
            "MUSIC_ALBUM_TITLE": "music album title",
            "MUSIC_RADIO_ID": "music radio id",
            "PHONE_NUMBER": "phone number",
            "ATTRIBUTE_EVENT": "attribute event",
            "ALARM_NAME": "alarm name",
            "SCHOOL": "school",
            "SIMILARITY": "similarity",
            "GROUP": "group",
            "METHOD_RECIPES": "method recipes",
            "RECIPES_TYPE_NUTRITION": "recipes type nutrition",
            "RECIPES_MEAL": "recipes meal",
            "RECIPES_RATING": "recipes rating",
            "RECIPES_QUALIFIER_NUTRITION": "recipes qualifier nutrition",
            "MUSIC_ALBUM_MODIFIER": "music album modifier",
            "AGE": "age",
            "ATTENDEE_EVENT": "attendee event",
            "CONTACT_METHOD": "contact method",
            "MUSIC_REWIND_TIME": "music rewind time",
            "RECIPES_SOURCE": "recipes source",
            "USER_ATTENDEE_EVENT": "user attendee event",
            "RECIPES_CUISINE": "recipes cuisine",
            "ATTENDEE": "attendee",
            "MUSIC_PLAYLIST_MODIFIER": "music playlist modifier",
            "MAJOR": "major",
            "TYPE_CONTACT": "type contact",
            "GENDER": "gender",
        }, 
    },
    "atis":{
        "string": {
            "fromloc.city_name": "from city",
            "toloc.city_name": "to city",
            "round_trip": "round trip",
            "cost_relative": "relative cost",
            "fare_amount": "fare amount",
            "arrive_date.month_name": "arrive month",
            "arrive_date.day_number": "arrive day",
            "stoploc.city_name": "stop city",
            "arrive_time.time_relative": "arrive relative time",
            "arrive_time.time": "arrive time",
            "toloc.state_code": "to state code",
            "meal_description": "meal description",
            "depart_date.month_name": "depart month",
            "depart_date.day_number": "depart day",
            "airline_name": "airline name",
            "depart_time.period_of_day": "depart period of day",
            "depart_date.day_name": "depart day",
            "toloc.state_name": "to state",
            "depart_time.time_relative": "depart relative time",
            "depart_time.time": "depart time",
            "toloc.airport_name": "to airport",
            "depart_date.date_relative": "depart relative date",
            "or": "or",
            "airline_code": "airline code",
            "class_type": "class type",
            "fromloc.airport_name": "from airport",
            "city_name": "city",
            "flight_mod": "flight mod",
            "meal": "meal",
            "economy": "economy",
            "fare_basis_code": "fare basis code",
            "depart_date.today_relative": "depart relative today",
            "flight_stop": "flight stop",
            "airport_code": "airport code",
            "fromloc.state_name": "from state",
            "connect": "connect",
            "arrive_date.day_name": "arrive day name",
            "fromloc.state_code": "from state code",
            "arrive_date.today_relative": "arrive relative today",
            "depart_date.year": "depart year",
            "depart_time.start_time": "depart start_time",
            "depart_time.end_time": "depart end_time",
            "arrive_time.start_time": "arrive start_time",
            "arrive_time.end_time": "arrive end_time",
            "flight_days": "flight days",
            "mod": "mod",
            "flight_number": "flight number",
            "meal_code": "meal code",
            "airport_name": "airport",
            "transport_type": "transport type",
            "state_code": "state code",
            "aircraft_code": "aircraft code",
            "toloc.country_name": "to country",
            "toloc.airport_code": "to airport code",
            "return_date.date_relative": "return relative date",
            "flight_time": "flight time",
            "fromloc.airport_code": "from airport code",
            "arrive_time.period_of_day": "arrive period of day",
            "depart_time.period_mod": "depart period mod",
            "return_date.day_name": "return day",
            "arrive_date.date_relative": "arrive relative date",
            "restriction_code": "restriction code",
            "arrive_time.period_mod": "arrive period mod",
            "period_of_day": "period of day",
            "stoploc.state_code": "stop state code",
            "time": "time",
            "today_relative": "relative today",
            "state_name": "state",
            "days_code": "days code",
            "time_relative": "relative time",
            "return_date.month_name": "return month",
            "return_date.day_number": "return day",
            "stoploc.airport_name": "stop airport",
            "day_name": "day",
            "month_name": "month",
            "day_number": "day",
            "return_time.period_mod": "return period mod",
            "return_time.period_of_day": "return period of day",
            "return_date.today_relative": "return relative today",
        },
    },
}

ner_tags = {
    "ace05r": {
        "string": {
            "ORG": "organization",
            "LOC": "location",
            "PER": "person",
            "VEH": "vehicle",
            "GPE": "geographical or political entities",
            "WEA": "weapon",
            "FAC": "facilities",
        },
        "special": {
            "ORG": "<ORG>",
            "LOC": "<LOC>",
            "PER": "<PER>",
            "VEH": "<VEH>",
            "GPE": "<GPE>",
            "WEA": "<WEA>",
            "FAC": "<FAC>",
        },
    },
    "ace04r": {
        "string": {
            "ORG": "organization",
            "LOC": "location",
            "PER": "person",
            "VEH": "vehicle",
            "GPE": "geographical or political entities",
            "WEA": "weapon",
            "FAC": "facilities",
        },
        "special": {
            "ORG": "<ORG>",
            "LOC": "<LOC>",
            "PER": "<PER>",
            "VEH": "<VEH>",
            "GPE": "<GPE>",
            "WEA": "<WEA>",
            "FAC": "<FAC>",
        },
    },
    "scierc": {
        "string": {
            "Generic": "general terms", 
            "Material": "resources", 
            "Method": "method", 
            "Metric": "metrics", 
            "OtherScientificTerm": "scientific", 
            "Task": "task",
        },
        "special": {
            "Generic": "<Generic>", 
            "Material": "<Material>", 
            "Method": "<Method>", 
            "Metric": "<Metric>", 
            "OtherScientificTerm": "<OtherScientificTerm>", 
            "Task": "<Task>",
        },
    }, 
}

relation_tags = {
    "ace05r": {
        "string": {
            "PART-WHOLE": "is part of",
            "PHYS": "locate at",
            "PER-SOC": "relationship between people",
            "ORG-AFF": "affiliation membership",
            "ART": "owner inventor manufacturer",
            "GEN-AFF": "resident origin",
        }, 
        "special": {
            "PART-WHOLE": "<PART-WHOLE>",
            "PHYS": "<PHYS>",
            "PER-SOC": "<PER-SOC>",
            "ORG-AFF": "<ORG-AFF>",
            "ART": "<ART>",
            "GEN-AFF": "<GEN-AFF>",
        }, 
    },
    "ace04r": {
        "string": {
            "EMP-ORG": "employment",
            "PHYS": "locate at",
            "PER-SOC": "relationship between people",
            "OTHER-AFF": "affiliation",
            "ART": "owner inventor manufacturer",
            "GPE-AFF": "resident or base location",
        }, 
        "special": {
            "EMP-ORG": "<EMP-ORG>",
            "PHYS": "<PHYS>",
            "PER-SOC": "<PER-SOC>",
            "OTHER-AFF": "<OTHER-AFF>",
            "ART": "<ART>",
            "GPE-AFF": "<GPE-AFF>",
        }, 
    },
    "scierc": {
        "string": {
            "COMPARE": "compare",
            "CONJUNCTION": "similar",
            "EVALUATE-FOR": "evaluate fore",
            "FEATURE-OF": "feature of",
            "HYPONYM-OF": "hyponym of",
            "PART-OF": "part of",
            "USED-FOR": "use for",
        }, 
        "special": {
            "COMPARE": "<COMPARE>",
            "CONJUNCTION": "<CONJUNCTION>",
            "EVALUATE-FOR": "<EVALUATE-FOR>",
            "FEATURE-OF": "<FEATURE-OF>",
            "HYPONYM-OF": "<HYPONYM-OF>",
            "PART-OF": "<PART-OF>",
            "USED-FOR": "<USED-FOR>",
        }, 
    },
}

patterns = {
    "ace05e": {
        "Business:Declare-Bankruptcy": ["Org"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Phone-Write": ["Entity", "Place"], 
        "Justice:Acquit": ["Defendant", "Adjudicator"], 
        "Justice:Appeal": ["Plaintiff", "Place", "Adjudicator"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Pardon": ["Defendant", "Adjudicator"], 
        "Justice:Release-Parole": ["Person", "Entity", "Place"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Movement:Transport": ["Artifact",  "Destination", "Origin", "Vehicle", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Ownership": ["Buyer", "Artifact", "Seller", "Place", "Beneficiary"], 
    }, 
    "ace05ep": {
        "Business:Declare-Bankruptcy": ["Org"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Phone-Write": ["Entity", "Place"], 
        "Justice:Acquit": ["Defendant", "Adjudicator"], 
        "Justice:Appeal": ["Plaintiff", "Place", "Adjudicator"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Pardon": ["Defendant", "Adjudicator"], 
        "Justice:Release-Parole": ["Person", "Entity", "Place"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Movement:Transport": ["Artifact",  "Destination", "Origin", "Vehicle", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Ownership": ["Buyer", "Artifact", "Seller", "Place", "Beneficiary"], 
    }, 
    "ace05zh": {
        "Business:Declare-Bankruptcy": ["Org", "Place"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Merge-Org": ["Org", "Place"], 
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Phone-Write": ["Entity", "Place"], 
        "Justice:Acquit": ["Defendant", "Adjudicator", "Place"], 
        "Justice:Appeal": ["Plaintiff", "Place", "Adjudicator"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Pardon": ["Defendant", "Adjudicator", "Place"], 
        "Justice:Release-Parole": ["Person", "Entity", "Place"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Movement:Transport": ["Artifact",  "Destination", "Origin", "Vehicle", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent", "Place"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Ownership": ["Buyer", "Artifact", "Seller", "Place", "Beneficiary"], 
    }, 
    "ere": {
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:End-Org": ["Org"], 
        "Business:Declare-Bankruptcy": ["Org"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Correspondence": ["Entity", "Place"], 
        "Contact:Broadcast": ["Entity", "Audience", "Place"], 
        "Contact:Contact": ["Entity", "Place"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Release-Parole": ["Person", "Agent", "Place"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Appeal": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Acquit": ["Defendant", "Adjudicator"], 
        "Justice:Pardon": ["Defendant", "Adjudicator"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Life:Divorce": ["Person", "Place"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Movement:Transport-Person": ["Person", "Destination", "Origin", "Instrument", "Agent"], 
        "Movement:Transport-Artifact": ["Artifact", "Destination", "Origin", "Agent"], 
        "Manufacture:Artifact": ["Artifact", "Agent", "Place"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent"], 
        "Personnel:Elect": ["Person", "Agent", "Place"], 
        "Transaction:Transfer-Ownership": ["Thing", "Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transaction": ["Giver", "Recipient", "Place", "Beneficiary"], 
    },
    "erees": {
        "Business:Start-Org": ["Agent", "Org", "Place"], 
        "Business:Merge-Org": ["Org"], 
        "Business:End-Org": ["Org", "Place"], 
        "Business:Declare-Bankruptcy": ["Org", "Place"], 
        "Conflict:Attack": ["Attacker", "Target", "Instrument", "Place", "Agent"], 
        "Conflict:Demonstrate": ["Entity", "Place"], 
        "Contact:Meet": ["Entity", "Place"], 
        "Contact:Correspondence": ["Entity", "Place"], 
        "Contact:Broadcast": ["Entity", "Audience", "Place"], 
        "Contact:Contact": ["Entity", "Place"], 
        "Justice:Arrest-Jail": ["Person", "Agent", "Place"], 
        "Justice:Release-Parole": ["Person", "Agent", "Place"], 
        "Justice:Trial-Hearing": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Charge-Indict": ["Defendant", "Prosecutor", "Place", "Adjudicator"], 
        "Justice:Sue": ["Defendant", "Plaintiff", "Place", "Adjudicator"], 
        "Justice:Convict": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Appeal": ["Defendant", "Place", "Adjudicator", "Prosecutor"], 
        "Justice:Sentence": ["Defendant", "Place", "Adjudicator"], 
        "Justice:Fine": ["Entity", "Place", "Adjudicator"], 
        "Justice:Execute": ["Person", "Agent", "Place"], 
        "Justice:Extradite": ["Person", "Destination", "Origin", "Agent"], 
        "Justice:Acquit": ["Defendant", "Adjudicator", "Place"], 
        "Justice:Pardon": ["Defendant", "Adjudicator", "Place"], 
        "Life:Be-Born": ["Person", "Place"], 
        "Life:Marry": ["Person", "Place"], 
        "Life:Divorce": ["Person"], 
        "Life:Injure": ["Agent", "Victim", "Instrument", "Place"], 
        "Life:Die": ["Agent", "Victim", "Instrument", "Place"], 
        "Movement:Transport-Person": ["Person", "Destination", "Origin", "Instrument", "Agent"], 
        "Movement:Transport-Artifact": ["Artifact", "Destination", "Origin", "Agent", "Instrument"], 
        "Manufacture:Artifact": ["Artifact", "Agent", "Place"], 
        "Personnel:Start-Position": ["Person", "Entity", "Place"], 
        "Personnel:End-Position": ["Person", "Entity", "Place"], 
        "Personnel:Nominate": ["Person", "Agent", "Place"], 
        "Personnel:Elect": ["Person", "Agent", "Place"], 
        "Transaction:Transfer-Ownership": ["Thing", "Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transfer-Money": ["Giver", "Recipient", "Place", "Beneficiary"], 
        "Transaction:Transaction": ["Giver", "Recipient", "Place", "Beneficiary"], 
    },
    "ace05r":{
        "PER": ['PART-WHOLE', 'PHYS', 'GEN-AFF', 'PER-SOC', 'ART', 'ORG-AFF'], 
        "ORG": ['PART-WHOLE', 'PHYS', 'GEN-AFF', 'ART', 'ORG-AFF'], 
        "GPE": ['PART-WHOLE', 'PHYS', 'ART', 'ORG-AFF'], 
        "LOC": ['PART-WHOLE', 'PHYS'], 
        "VEH": ['PART-WHOLE'], 
        "FAC": ['PART-WHOLE', 'PHYS'], 
        "WEA": ['PART-WHOLE'],
    },
    "ace04r":{
        "PER": ['EMP-ORG', 'PHYS', 'GPE-AFF', 'PER-SOC', 'ART', 'OTHER-AFF'], 
        "GPE": ['PHYS', 'GPE-AFF', 'ART', 'EMP-ORG', "OTHER-AFF"], 
        "ORG": ['GPE-AFF', 'PHYS', 'ART', 'EMP-ORG', "OTHER-AFF"], 
        "LOC": ['PHYS', 'GPE-AFF', 'OTHER-AFF'], 
        "VEH": ['PHYS', 'ART'], 
        "FAC": ['PHYS'], 
        "WEA": ['PHYS'],
    },
    "mtop": {
        "ADD_TIME_TIMER": ["DATE_TIME", "METHOD_TIMER", "TIMER_NAME"],
        "ADD_TO_PLAYLIST_MUSIC": ["MUSIC_PLAYLIST_TITLE", "MUSIC_PROVIDER_NAME", "MUSIC_TYPE"],
        "ANSWER_CALL": ["CONTACT", "DATE_TIME"],
        "CANCEL_CALL": [],
        "CANCEL_MESSAGE": ["RECIPIENT", "TYPE_CONTENT"],
        "CREATE_ALARM": ["ALARM_NAME", "AMOUNT", "DATE_TIME", "ORDINAL", "PERIOD"],
        "CREATE_CALL": ["CONTACT", "GROUP", "NAME_APP", "ORDINAL", "PHONE_NUMBER"],
        "CREATE_PLAYLIST_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PLAYLIST_TITLE", "MUSIC_TYPE"],
        "CREATE_REMINDER": ["AMOUNT", "DATE_TIME", "LOCATION", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "CREATE_TIMER": ["AMOUNT", "DATE_TIME", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "DELETE_ALARM": ["ALARM_NAME", "AMOUNT", "DATE_TIME", "ORDINAL", "PERIOD"],
        "DELETE_PLAYLIST_MUSIC": ["MUSIC_GENRE", "MUSIC_PLAYLIST_TITLE", "MUSIC_TYPE"],
        "DELETE_REMINDER": ["AMOUNT", "DATE_TIME", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "DELETE_TIMER": ["AMOUNT", "DATE_TIME", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "DISLIKE_MUSIC": ["MUSIC_TYPE"],
        "DISPREFER": ["CATEGORY_EVENT"],
        "END_CALL": ["CONTACT"],
        "FAST_FORWARD_MUSIC": ["MUSIC_REWIND_TIME", "MUSIC_TYPE", "ORDINAL"],
        "FOLLOW_MUSIC": ["MUSIC_ARTIST_NAME"],
        "GET_AGE": ["AGE", "CONTACT", "CONTACT_RELATED", "DATE_TIME", "TYPE_RELATION"],
        "GET_AIRQUALITY": ["DATE_TIME", "WEATHER_ATTRIBUTE"],
        "GET_ALARM": ["ALARM_NAME", "AMOUNT", "DATE_TIME", "ORDINAL", "PERIOD"],
        "GET_ATTENDEE_EVENT": ["ATTENDEE_EVENT", "TITLE_EVENT"],
        "GET_AVAILABILITY": ["CONTACT"],
        "GET_CALL": ["AMOUNT", "CONTACT", "DATE_TIME", "ORDINAL"],
        "GET_CALL_CONTACT": ["DATE_TIME"],
        "GET_CALL_TIME": ["CONTACT", "DATE_TIME"],
        "GET_CATEGORY_EVENT": ["TITLE_EVENT"],
        "GET_CONTACT": ["CONTACT", "CONTACT_RELATED", "DATE_TIME", "EDUCATION_DEGREE", "EMPLOYER", "JOB", "LIFE_EVENT", "LOCATION", "MAJOR", "SCHOOL", "TYPE_CONTACT", "TYPE_RELATION"],
        "GET_CONTACT_METHOD": ["CONTACT", "CONTACT_METHOD"],
        "GET_DATE_TIME_EVENT": ["CATEGORY_EVENT", "DATE_TIME", "LOCATION", "ORDINAL", "TITLE_EVENT"],
        "GET_DETAILS_NEWS": ["DATE_TIME", "NEWS_REFERENCE", "NEWS_SOURCE", "NEWS_TOPIC", "NEWS_TYPE"],
        "GET_EDUCATION_DEGREE": ["CONTACT", "EDUCATION_DEGREE", "LIFE_EVENT", "SCHOOL"],
        "GET_EDUCATION_TIME": ["CONTACT", "CONTACT_RELATED", "DATE_TIME", "EDUCATION_DEGREE", "LIFE_EVENT", "SCHOOL", "TYPE_RELATION"],
        "GET_EMPLOYER": ["CONTACT", "CONTACT_RELATED", "DATE_TIME", "EMPLOYER", "LOCATION", "TYPE_RELATION"],
        "GET_EMPLOYMENT_TIME": ["CONTACT", "DATE_TIME", "EMPLOYER", "JOB"],
        "GET_EVENT": ["ATTENDEE_EVENT", "ATTRIBUTE_EVENT", "CATEGORY_EVENT", "DATE_TIME", "LOCATION", "SIMILARITY", "TITLE_EVENT", "USER_ATTENDEE_EVENT"],
        "GET_GENDER": ["CONTACT", "GENDER"],
        "GET_GROUP": ["CONTACT"],
        "GET_INFO_CONTACT": ["CONTACT", "CONTACT_RELATED", "TYPE_RELATION"],
        "GET_INFO_RECIPES": ["METHOD_RECIPES", "RECIPES_ATTRIBUTE", "RECIPES_COOKING_METHOD", "RECIPES_CUISINE", "RECIPES_DIET", "RECIPES_DISH", "RECIPES_EXCLUDED_INGREDIENT", "RECIPES_INCLUDED_INGREDIENT", "RECIPES_MEAL", "RECIPES_QUALIFIER_NUTRITION", "RECIPES_RATING", "RECIPES_SOURCE", "RECIPES_TYPE_NUTRITION", "RECIPES_UNIT_MEASUREMENT", "RECIPES_UNIT_NUTRITION"],
        "GET_JOB": ["CONTACT", "JOB"],
        "GET_LANGUAGE": ["CONTACT"],
        "GET_LIFE_EVENT": ["CONTACT", "LIFE_EVENT"],
        "GET_LIFE_EVENT_TIME": ["CONTACT", "DATE_TIME", "LIFE_EVENT"],
        "GET_LOCATION": ["CONTACT", "CONTACT_RELATED", "DATE_TIME", "EMPLOYER", "JOB", "LIFE_EVENT", "LOCATION", "ORDINAL", "TITLE_EVENT", "TYPE_RELATION"],
        "GET_LYRICS_MUSIC": ["MUSIC_TYPE"],
        "GET_MAJOR": ["CONTACT", "MAJOR", "SCHOOL"],
        "GET_MESSAGE": ["CONTACT", "DATE_TIME", "GROUP", "NAME_APP", "ORDINAL", "RECIPIENT", "SENDER", "TYPE_CONTENT"],
        "GET_MESSAGE_CONTACT": ["CONTENT_EXACT", "DATE_TIME", "NAME_APP", "ORDINAL", "RECIPIENT", "TYPE_CONTENT"],
        "GET_MUTUAL_FRIENDS": ["CONTACT_RELATED", "TYPE_RELATION"],
        "GET_RECIPES": ["DATE_TIME", "RECIPES_ATTRIBUTE", "RECIPES_COOKING_METHOD", "RECIPES_CUISINE", "RECIPES_DIET", "RECIPES_DISH", "RECIPES_EXCLUDED_INGREDIENT", "RECIPES_INCLUDED_INGREDIENT", "RECIPES_MEAL", "RECIPES_QUALIFIER_NUTRITION", "RECIPES_RATING", "RECIPES_SOURCE", "RECIPES_TYPE", "RECIPES_TYPE_NUTRITION", "RECIPES_UNIT_NUTRITION"],
        "GET_REMINDER": ["AMOUNT", "DATE_TIME", "METHOD_RETRIEVAL_REMINDER", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "GET_REMINDER_AMOUNT": ["DATE_TIME", "LOCATION", "PERSON_REMINDED", "TODO"],
        "GET_REMINDER_DATE_TIME": ["DATE_TIME", "METHOD_RETRIEVAL_REMINDER", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "GET_REMINDER_LOCATION": ["DATE_TIME", "METHOD_RETRIEVAL_REMINDER", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "GET_STORIES_NEWS": ["DATE_TIME", "NEWS_CATEGORY", "NEWS_REFERENCE", "NEWS_SOURCE", "NEWS_TOPIC", "NEWS_TYPE"],
        "GET_SUNRISE": ["DATE_TIME", "LOCATION"],
        "GET_SUNSET": ["DATE_TIME", "LOCATION"],
        "GET_TIMER": ["AMOUNT", "DATE_TIME", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "GET_TRACK_INFO_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_PROVIDER_NAME", "MUSIC_TRACK_TITLE", "MUSIC_TYPE", "ORDINAL"],
        "GET_UNDERGRAD": ["CONTACT", "CONTACT_RELATED", "DATE_TIME", "LOCATION", "SCHOOL", "TYPE_RELATION"],
        "GET_WEATHER": ["DATE_TIME", "LOCATION", "WEATHER_ATTRIBUTE", "WEATHER_TEMPERATURE_UNIT"],
        "HELP_REMINDER": [],
        "HOLD_CALL": ["CONTACT", "DATE_TIME"],
        "IGNORE_CALL": ["CONTACT", "DATE_TIME"],
        "IS_TRUE_RECIPES": ["METHOD_RECIPES", "RECIPES_ATTRIBUTE", "RECIPES_COOKING_METHOD", "RECIPES_DIET", "RECIPES_DISH", "RECIPES_EXCLUDED_INGREDIENT", "RECIPES_INCLUDED_INGREDIENT", "RECIPES_QUALIFIER_NUTRITION", "RECIPES_TYPE_NUTRITION", "RECIPES_UNIT_NUTRITION"],
        "LIKE_MUSIC": ["MUSIC_TYPE"],
        "LOOP_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_TRACK_TITLE", "MUSIC_TYPE"],
        "MERGE_CALL": [],
        "PAUSE_MUSIC": ["MUSIC_PROVIDER_NAME", "MUSIC_TYPE"],
        "PAUSE_TIMER": ["AMOUNT", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "PLAY_MEDIA": ["MUSIC_ARTIST_NAME", "MUSIC_TRACK_TITLE"],
        "PLAY_MUSIC": ["MUSIC_ALBUM_MODIFIER", "MUSIC_ALBUM_TITLE", "MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PLAYLIST_MODIFIER", "MUSIC_PLAYLIST_TITLE", "MUSIC_PROVIDER_NAME", "MUSIC_RADIO_ID", "MUSIC_TRACK_TITLE", "MUSIC_TYPE"],
        "PREFER": ["CATEGORY_EVENT"],
        "PREVIOUS_TRACK_MUSIC": ["MUSIC_PROVIDER_NAME", "MUSIC_TYPE", "ORDINAL"],
        "QUESTION_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PROVIDER_NAME", "MUSIC_TRACK_TITLE", "MUSIC_TYPE"],
        "QUESTION_NEWS": ["DATE_TIME", "NEWS_SOURCE", "NEWS_TOPIC", "NEWS_TYPE"],
        "REMOVE_FROM_PLAYLIST_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_TYPE"],
        "REPEAT_ALL_MUSIC": [],
        "REPEAT_ALL_OFF_MUSIC": [],
        "REPLAY_MUSIC": ["MUSIC_ALBUM_TITLE", "MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PROVIDER_NAME", "MUSIC_TRACK_TITLE", "MUSIC_TYPE"],
        "RESTART_TIMER": ["AMOUNT", "DATE_TIME", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "RESUME_CALL": ["CONTACT"],
        "RESUME_MUSIC": ["MUSIC_TYPE"],
        "RESUME_TIMER": ["DATE_TIME", "METHOD_TIMER", "ORDINAL", "TIMER_NAME"],
        "REWIND_MUSIC": ["MUSIC_REWIND_TIME", "MUSIC_TYPE"],
        "SEND_MESSAGE": ["CONTACT", "CONTENT_EXACT", "GROUP", "NAME_APP", "ORDINAL", "RECIPIENT", "TYPE_CONTENT"],
        "SET_AVAILABLE": ["CONTACT"],
        "SET_DEFAULT_PROVIDER_CALLING": ["NAME_APP"],
        "SET_DEFAULT_PROVIDER_MUSIC": ["MUSIC_PROVIDER_NAME"],
        "SET_RSVP_INTERESTED": ["ORDINAL", "TITLE_EVENT"],
        "SET_RSVP_NO": ["ORDINAL", "TITLE_EVENT"],
        "SET_RSVP_YES": ["ORDINAL", "TITLE_EVENT"],
        "SET_UNAVAILABLE": [],
        "SHARE_EVENT": ["CATEGORY_EVENT", "CONTACT", "ORDINAL", "TITLE_EVENT"],
        "SILENCE_ALARM": ["ALARM_NAME", "AMOUNT", "ORDINAL", "PERIOD"],
        "SKIP_TRACK_MUSIC": ["MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PROVIDER_NAME", "MUSIC_TYPE", "ORDINAL"],
        "SNOOZE_ALARM": ["ALARM_NAME", "AMOUNT", "DATE_TIME", "ORDINAL"],
        "START_SHUFFLE_MUSIC": ["MUSIC_ALBUM_TITLE", "MUSIC_ARTIST_NAME", "MUSIC_GENRE", "MUSIC_PLAYLIST_TITLE", "MUSIC_PROVIDER_NAME", "MUSIC_TYPE"],
        "STOP_MUSIC": ["MUSIC_PROVIDER_NAME", "MUSIC_TYPE"],
        "STOP_SHUFFLE_MUSIC": [],
        "SUBTRACT_TIME_TIMER": ["DATE_TIME", "METHOD_TIMER", "TIMER_NAME"],
        "SWITCH_CALL": ["CONTACT"],
        "UNLOOP_MUSIC": ["MUSIC_TYPE"],
        "UPDATE_ALARM": ["ALARM_NAME", "AMOUNT", "DATE_TIME", "ORDINAL", "PERIOD"],
        "UPDATE_CALL": ["CONTACT", "CONTACT_ADDED", "CONTACT_REMOVED"],
        "UPDATE_METHOD_CALL": ["CONTACT"],
        "UPDATE_REMINDER": ["AMOUNT", "DATE_TIME", "LOCATION", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "UPDATE_REMINDER_DATE_TIME": ["AMOUNT", "ATTENDEE", "DATE_TIME", "LOCATION", "ORDINAL", "PERSON_REMINDED", "TODO"],
        "UPDATE_REMINDER_LOCATION": ["DATE_TIME", "LOCATION", "TODO"],
        "UPDATE_REMINDER_TODO": ["AMOUNT", "DATE_TIME", "PERSON_REMINDED", "TODO"],
        "UPDATE_TIMER": ["AMOUNT", "DATE_TIME", "METHOD_TIMER", "TIMER_NAME"],
    },
    "scierc":{
        'OtherScientificTerm': ['CONJUNCTION', 'FEATURE-OF', 'USED-FOR', 'PART-OF', 'HYPONYM-OF', 'COMPARE', 'EVALUATE-FOR'],
        'Material': ['HYPONYM-OF', 'FEATURE-OF', 'USED-FOR', 'CONJUNCTION', 'PART-OF', 'EVALUATE-FOR', 'COMPARE'],
        'Method': ['USED-FOR', 'CONJUNCTION', 'PART-OF', 'EVALUATE-FOR', 'HYPONYM-OF', 'COMPARE', 'FEATURE-OF'],
        'Generic': ['COMPARE', 'USED-FOR', 'HYPONYM-OF', 'CONJUNCTION', 'EVALUATE-FOR', 'PART-OF'],
        'Task': ['CONJUNCTION', 'PART-OF', 'USED-FOR', 'HYPONYM-OF', 'EVALUATE-FOR', 'FEATURE-OF', 'COMPARE'],                    
        'Metric': ['EVALUATE-FOR', 'CONJUNCTION', 'HYPONYM-OF', 'FEATURE-OF', 'USED-FOR']
    },
}

type_constraint = {
    # (subject, relation): possible object
    "ace05r": {
        ('PER', 'ORG-AFF'): ['ORG', 'GPE', 'PER', 'FAC'],
        ('PER', 'PART-WHOLE'): ['ORG'],
        ('PER', 'PHYS'): ['GPE', 'FAC', 'LOC'],
        ('PER', 'PER-SOC'): ['PER'], 
        ('PER', 'ART'): ['VEH', 'FAC', 'WEA', 'GPE'],
        ('PER', 'GEN-AFF'): ['GPE', 'LOC', 'PER', 'ORG'],  
        ('ORG', 'ART'): ['VEH', 'FAC', 'WEA'], 
        ('ORG', 'GEN-AFF'): ['GPE', 'LOC'], 
        ('ORG', 'ORG-AFF'): ['ORG', 'GPE'], 
        ('ORG', 'PART-WHOLE'): ['GPE', 'ORG', 'LOC'], 
        ('ORG', 'PHYS'): ['GPE', 'FAC'], 
        ('GPE', 'PART-WHOLE'): ['GPE', 'LOC'], 
        ('GPE', 'PHYS'): ['GPE', 'LOC'], 
        ('GPE', 'ORG-AFF'): ['ORG'], 
        ('GPE', 'ART'): ['WEA', 'VEH', 'FAC'],
        ('LOC', 'PART-WHOLE'): ['GPE', 'LOC', 'FAC'], 
        ('LOC', 'PHYS'): ['LOC', 'GPE'], 
        ('VEH', 'PART-WHOLE'): ['VEH'],
        ('FAC', 'PHYS'): ['GPE', 'FAC', 'LOC'], 
        ('FAC', 'PART-WHOLE'): ['GPE', 'LOC', 'FAC', 'ORG'], 
        ('WEA', 'PART-WHOLE'): ['WEA', 'VEH'],
    },
    "ace04r": {
        ('PER', 'ART'): ['VEH', 'WEA', 'FAC'],
        ('PER', 'EMP-ORG'): ['GPE', 'LOC', 'ORG', 'PER', 'FAC'],
        ('PER', 'GPE-AFF'): ['GPE', 'LOC', 'PER'],
        ('PER', 'OTHER-AFF'): ['PER', 'GPE', 'ORG', 'FAC', 'LOC'],
        ('PER', 'PER-SOC'): ['PER'],
        ('PER', 'PHYS'): ['GPE', 'FAC', 'PER', 'LOC', 'ORG', 'VEH'],  
        ('ORG', 'ART'): ['VEH', 'FAC', 'WEA'], 
        ('ORG', 'GPE-AFF'): ['GPE', 'LOC'], 
        ('ORG', 'EMP-ORG'): ['GPE', 'ORG', 'PER'], 
        ('ORG', 'OTHER-AFF'): ['PER', 'ORG', 'GPE', 'LOC'], 
        ('ORG', 'PHYS'): ['GPE', 'LOC', 'ORG', 'FAC'], 
        ('GPE', 'EMP-ORG'): ['GPE', 'ORG'], 
        ('GPE', 'PHYS'): ['GPE', 'LOC'], 
        ('GPE', 'GPE-AFF'): ['GPE', 'LOC', 'FAC'], 
        ('GPE', 'ART'): ['WEA', 'VEH', 'FAC', 'GPE', 'LOC'],
        ('GPE', 'OTHER-AFF'): ['PER', 'GPE', 'ORG'],
        ('LOC', 'GPE-AFF'): ['GPE'], 
        ('LOC', 'OTHER-AFF'): ['PER', 'GPE', 'ORG'], 
        ('LOC', 'PHYS'): ['LOC', 'GPE'], 
        ('VEH', 'ART'): ['GPE'],
        ('VEH', 'PHYS'): ['GPE', 'VEH', 'FAC', 'LOC'],
        ('FAC', 'PHYS'): ['GPE', 'FAC', 'LOC'], 
        ('WEA', 'PHYS'): ['GPE', 'LOC', 'VEH', 'WEA', 'FAC'],
    },
    "scierc": {
        ('Generic', 'COMPARE'): ['Generic', 'Method', 'Metric', 'OtherScientificTerm', 'Material', 'Task'],
        ('Generic', 'CONJUNCTION'): ['Generic', 'Method', 'OtherScientificTerm', 'Material'],
        ('Generic', 'EVALUATE-FOR'): ['Generic', 'Method', 'OtherScientificTerm', 'Task'],
        ('Generic', 'HYPONYM-OF'): ['Method', 'Generic', 'Task', 'OtherScientificTerm'],
        ('Generic', 'PART-OF'): ['OtherScientificTerm', 'Method', 'Material', 'Generic', 'Task'],
        ('Generic', 'USED-FOR'): ['Task', 'Generic', 'OtherScientificTerm', 'Method', 'Material', 'Metric'],
        ('Material', 'COMPARE'): ['OtherScientificTerm', 'Material', 'Task'],
        ('Material', 'CONJUNCTION'): ['Material', 'Generic', 'Method', 'OtherScientificTerm'],
        ('Material', 'EVALUATE-FOR'): ['Method', 'Generic', 'Task', 'Metric'],
        ('Material', 'FEATURE-OF'): ['Generic', 'OtherScientificTerm', 'Material', 'Method', 'Task'],
        ('Material', 'HYPONYM-OF'): ['Material', 'Generic', 'Task', 'OtherScientificTerm'],
        ('Material', 'PART-OF'): ['Material', 'Generic', 'Task'],
        ('Material', 'USED-FOR'): ['Generic', 'OtherScientificTerm', 'Method', 'Task', 'Material', 'Metric'],
        ('Method', 'COMPARE'): ['Method', 'Generic', 'OtherScientificTerm'],
        ('Method', 'CONJUNCTION'): ['Method', 'OtherScientificTerm', 'Generic', 'Task'],
        ('Method', 'EVALUATE-FOR'): ['OtherScientificTerm', 'Method', 'Generic', 'Metric'],
        ('Method', 'FEATURE-OF'): ['Task', 'OtherScientificTerm', 'Method', 'Generic'],
        ('Method', 'HYPONYM-OF'): ['Method', 'Generic', 'Task', 'OtherScientificTerm'],
        ('Method', 'PART-OF'): ['Method', 'Generic', 'OtherScientificTerm', 'Task'],
        ('Method', 'USED-FOR'): ['OtherScientificTerm', 'Task', 'Method', 'Material', 'Generic', 'Metric'],
        ('Metric', 'CONJUNCTION'): ['Metric', 'Generic', 'Method', 'OtherScientificTerm', 'Material'],
        ('Metric', 'EVALUATE-FOR'): ['Material', 'Generic', 'Method', 'OtherScientificTerm', 'Task', 'Metric'],
        ('Metric', 'FEATURE-OF'): ['Generic', 'Method', 'Metric', 'Material', 'Task', 'OtherScientificTerm'],
        ('Metric', 'HYPONYM-OF'): ['Metric', 'OtherScientificTerm', 'Method', 'Generic'],
        ('Metric', 'USED-FOR'): ['Generic', 'Task', 'OtherScientificTerm', 'Method', 'Material'],
        ('OtherScientificTerm', 'COMPARE'): ['OtherScientificTerm', 'Material', 'Generic'],
        ('OtherScientificTerm', 'CONJUNCTION'): ['OtherScientificTerm', 'Method', 'Material', 'Generic', 'Metric', 'Task'],
        ('OtherScientificTerm', 'EVALUATE-FOR'): ['Method', 'Generic'],
        ('OtherScientificTerm', 'FEATURE-OF'): ['Material', 'OtherScientificTerm', 'Generic', 'Method', 'Task', 'Metric'],
        ('OtherScientificTerm', 'HYPONYM-OF'): ['OtherScientificTerm', 'Generic', 'Method', 'Task', 'Material'],
        ('OtherScientificTerm', 'PART-OF'): ['Method', 'Material', 'Task', 'OtherScientificTerm', 'Generic', 'Metric'], 
        ('OtherScientificTerm', 'USED-FOR'): ['Task', 'Method', 'Metric', 'OtherScientificTerm', 'Generic', 'Material'],
        ('Task', 'COMPARE'): ['Task'], 
        ('Task', 'CONJUNCTION'): ['Task', 'Method', 'OtherScientificTerm'],
        ('Task', 'EVALUATE-FOR'): ['Generic', 'Task', 'Method', 'OtherScientificTerm', 'Metric'],
        ('Task', 'FEATURE-OF'): ['Generic', 'Task', 'Method', 'OtherScientificTerm', 'Material'],
        ('Task', 'HYPONYM-OF'): ['Generic', 'Task'],
        ('Task', 'PART-OF'): ['Task', 'Generic', 'Method'],
        ('Task', 'USED-FOR'): ['Generic', 'OtherScientificTerm', 'Task', 'Material', 'Metric', 'Method'],
    }
}